from pyramid.config import Configurator
def main(global_config, **settings):
    config = Configurator(settings=settings)

    config.add_route('index', '/')
    config.add_route('msglog', '/msglog/{device_id}/{sub_id}')
    config.add_route('msglogview', '/msglogview/{device_id}/{sub_id}')
    config.add_route('msglogtableview', '/msglogtableview/{device_id}/{sub_id}')

    config.add_route('get_data', '/get_data')
    config.add_route('update_form', '/update_form')
    config.add_route('api/cbsd_list', '/api/data')
    config.add_route('api/dpa_list', '/api/dpa_list')
    config.add_route('api/msg_list', '/api/msg_list')
    config.add_route('api/grant_list', '/api/grant_list')
    config.add_route('api/regist', '/api/regist')
    config.add_route('api/deregist', '/api/deregist')
    config.add_route('api/cbsd_delete', '/api/cbsd_delete')
    config.add_route('api/grant', '/api/grant')
    config.add_route('api/relinquishment', '/api/relinquishment')
    config.add_route('api/spectrumInquery', '/api/spectrumInquery')
    config.add_route('ws', '/ws')
    config.add_route('api/prop_load', '/api/prop_load')
    config.add_route('api/prop_update', '/api/prop_update')
    config.add_route('api/get_msg_list_part', '/api/get_msg_list_part')
    config.include('pyramid_jinja2')
    config.add_static_view(name='static', path='cbsd_emul_v1_0:static', cache_max_age=3600)
    config.scan('cbsd_emul_v1_0.views')
    return config.make_wsgi_app()